name: flexglow_app
description: Yippee flexglow. Made by Ernesto Gomez netog@umich.edu

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  cupertino_icons: ^1.0.8
  animations: ^2.0.11

  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  oscilloscope: ^0.2.0+1
  
  flutter_blue_plus: ^1.33.6
  flutter_colorpicker: ^1.1.0

  share_plus: ^10.1.2
  csv: ^6.0.0
  fl_chart: ^0.69.2

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/